### ISSUE TITLE
Output of InSpec shell command with \r\n

### ISSUE THREAD

**Issue by magdamag** [jrbeilke/packer-provisioner-inspec#12]
Hi,

Anyone experiencing InSpec command output to get \r\n instead of \n?
E.g. this native InSpec _service_ resource test fails for me since the returned output has \r\n:
```def info(service_name)
      # check if service is installed
      # read all available services via ls /etc/init.d/
      srvlist = inspec.command('ls -1 /etc/init.d/')
      return nil if srvlist.exit_status != 0

      # check if the service is in list
      service = srvlist.stdout.split("\n").select { |srv| srv == service_name }

      # abort if we could not find any service
      return nil if service.empty?
```

Anyone experienced having that issue? Or is that something with the shell / box that InSpec runs on?

**Comment by jrbeilke** [comment]
Which Packer builder are you using and which OS are you running on the host system?

**Comment by pielu** [comment]
Oops, had someone else's creds on github while creating issue.
The guest OS is CentOS 6.10 and happens across the builders (AWS, VMware, VirtualBox etc). The host OS is CentOS 7.5.

**Comment by pielu** [comment]
Actually, I found a case with CentOS 6 guest (still same host) where lines get properly only \n. That would suggest it is guest environmental issue in the end...
