### ISSUE TITLE
Create release artefacts

### ISSUE THREAD

**Issue by fatmcgav** [jrbeilke/packer-provisioner-inspec#2]
@jrbeilke First, cheers for writing this plugin, it's working great for me soo far. 

One minor pain point is the fact that there's no pre-built release artefacts. 
Would you be able to do a release and provide a set of pre-built artefacts for the common OS and arch combinations?

I guess you could also look at plumbing it via TravisCI if that was easier...

**Comment by jrbeilke** [comment]
Definitely. I'm planning to hook up Travis CI anyways so I'll see if I can also have it deploy to GitHub.

**Comment by fatmcgav** [comment]
Yeh, it's definitely possible to get Travis to publish release artifacts to
GitHub... 😀

Let me know if I can offer any assistance.

And thanks again...

**Comment by jrbeilke** [comment]
Got the Travis CI build working and adding artifacts to Github releases.

**Comment by fatmcgav** [comment]
Awesome, cheers for that @jrbeilke
