### ISSUE TITLE
Support inspec exit codes

### ISSUE THREAD

**Issue by atward** [jrbeilke/packer-provisioner-inspec#6]
> https://github.com/inspec/inspec/issues/1825#issuecomment-382650911
> ```
> 0 run ok + all passed:
> 100 run okay + failures
> 101 run okay + skipped only
> ```

Current plugin requires inspec to exit with 0. Users should be able to permit skipped tests (exit 101).

**Comment by jrbeilke** [comment]
As a workaround for now you can pass the `--no-distinct-exit` option through extra_arguments to get exit code 1 on test or any other failure, exit 0 on normal or skip-only runs.

**Comment by atward** [comment]
`--no-distinct-exit` requires inspec 2.2.27+
Current stable chefdk (3.1.0) is still stuck on inspec 2.1. Will hold out for a new release.

Looking into this further there doesn't seem to be a simple way to get a platform independent exit code golang os/exec

**Comment by jrbeilke** [comment]
FYI chefdk versions 3.1.5 and higher now include inspec with support for the `--no-distinct-exit option`
